# Generated by Django 6.0.1 on 2026-01-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anniversary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rsvp",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="rsvp",
            name="attending",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rsvp",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
